### ISSUE TITLE
Weathermap doesn't use cactis page refresh intervall

### ISSUE THREAD

**Issue by momorientes** [howardjones/network-weathermap#17]
Weathermap uses a static value of 300s not the configurable page_refresh intervall

**Comment by howardjones** [comment]
In the weathermap plugin pages of Cacti, it uses the Cacti refresh interval. In a standalone HTML output file (not the normal method with Cacti) it doesn't, because you may not even *have* cacti...

Does that tie up with what you are seeing, or can you provide more details? (like, which page is refreshing at static 300s)

**Comment by momorientes** [comment]
I'm using version 0.97c within cacti, I had to manually set the update intervall in:  cacti/site/plugins/weathermap/weathermap
cacti/site/plugins/weathermap/weathermap.html  
to my desired intervall, otherwise all my maps wouldn't refresh when viewed in cacti

**Comment by howardjones** [comment]
Why are you using the command-line tool, if you are viewing maps in Cacti?
