### ISSUE TITLE
Feature request: more parsing of {node:....} etc

### ISSUE THREAD

**Issue by jrbinks** [howardjones/network-weathermap#28]
Hi Howie etc,

Can you extend parsing so that  {node:...} and {link:...} can be used in more places, particularly variable assignments?  I want to have this construct:

LINK CurSX_McC1-10G
        NODES mccance1 cursx
        SET src mccance1
        SET ip {node:mccance1:ip}
        SET group {node:mccance1:group}

but SET ip {node...} doesn't get replaced.

I've already defined variable 'ip' on the node so it can be used in the node OVERLIBGRAPH (inherited from NODE DEFAULT, for CPU), so I just want to be able to call that value back so it will get used for the link OVERLIBGRAPH too (inherited from LINK DEFAULT).

At the moment, I have to explicitly SET ip with the actual IP address on the link as well in order for OVERLIBGRAPH to work, but since I've already had to do that on the node, that's just repeating information.  And I like to avoid that at all costs!

Thanks for considering.  Love weathermap.

**Comment by howardjones** [comment]
It's possible, but takes quite a bit of change to avoid recursive loops and problems with forward-references (what if node:mccance1 is further down in the file? At the moment that would mean it was undefined). I agree that it'd be useful though, and I'll add it to the list. 

*However*, for your particular issue, you might like to try: `{node:_linkstart_:ip}` in your LINK DEFAULT, which should refer to the first node in the link. This is in 0.97b at least, although I don't see it in the manual, which is odd.

**Comment by jrbinks** [comment]
Oh, yes, I have never seen that.  So {node:_linkstart_:ip} references the first item in the NODES line in a LINK?

OK ... yes that works.  I use the aged routers2.cgi for my graphs: Now in LINK DEFAULT I can have:

        OVERLIBGRAPH /cgi-bin/routers2.cgi?rtr={node:_linkstart_:group}%2F{link:this:src}.cfg&bars=Cami&xgtype=d&xgstyle=l2&if={node:_linkstart_:ip}_{link:this:int}&page=image&xmtype=options

and that works fine, referencing the parameters on the node for the first NODES line item.  Excellent!
Please document it!  Are there any other magical items like this?

Hmm, it mostly works.  Works for OVERLIBGRAPH, having problems with INFOURL though, can you check it is parsed properly in that context?

Regarding forward references, my NODEs are always defined before my LINKs, that seems to be sensible practice to me.

In fact I was going to add another feature request, which was more tentative (I have just inserted it below), but I think _linkstart_ means I don't need it now, for this use case at least.  Will check.

Thanks!

"In my previous feature request, I mention I had:

LINK CurSX_McC1-10G
NODES mccance1 cursx
SET src mccance1
SET ip {node:mccance1:ip}
SET group {node:mccance1:group}

In my goal to minimise duplication, what I would like to write is:

LINK CurSX_McC1-10G
SET src mccance1
NODES {link:this:src} cursx
SET ip {node:{link:this:src}:ip}
SET group {node:{link:this:src}:group}

Now I only have to change SET src and all references."

**Comment by howardjones** [comment]
There's `_linkend_` for the other end of the link. At the time, I was working towards being able to treat a node and a series of subnodes (e.g. cpu/memory stats) as a group in some way, so that templates can be more effective. That's why there's a {node:parent:...} too. But then I got concerned that you'd really need to be able to use these in a TARGET line, and that allows anyone with access to the Cacti admin screen to feed arbitrary data to the data source plugin, which requires a bit more care.

There's a single function called ProcessString that deals with all of these tokens, so what works in one place ought to work in another, with a few exceptions (variables set by plugins are treated differently from ones set by the user).

Anyway... 

Yes, yours are defined in that order, but there's no actual requirement for it, which means that at least two passes are required to get the right values. This is where moving to something like XML, YAML, JSON etc, which has an actual document structure would be useful, fully separating the 'read from a file and figure out the structure' part from the 'do things with the structure' part.

This last one is super-hacky though! These tokens are already doing double duty as sort-of-macro substitutions and sort-of-variables. Using that kind of structure would mean delaying all the error checking for a link until after the whole file is read, too (back to the YAML/JSON thing above). I would look at something like M4 or cpp for this kind of thing, really, as it's quite specific to your use-case.

As you say, though, by changing the NODES line to be the single mention of mccance1, I think linkstart will get you to where you need to be.

**Comment by misiek08** [comment]
Maybe we can just say "if you need to use nodes data, put them before links
definitions. Unknown variables will raise error".
That will keep single parsing cycle and support what user need.

**Comment by jrbinks** [comment]
I agree that's probably a good compromise at this stage.

**Comment by jrbinks** [comment]
Aha, my problem with INFOURL is to do with my LINK templates, which don't have NODEs defined, so `{node:_linkstart_:ip}` doesn't refer to anything.

Error is:

WARNING: /usr/local/weathermap/core.conf: ProcessString: {node:_linkstart_:ip} refers to unknown item (context is link:DEFAULT) [WMWARN05]

repeated 4 times for each LINK template).  Besides the default one, templates simply look like:

LINK 100M
        BANDWIDTH 100M
        WIDTH 1

I tried fiddling around with NODES dummy1 dummy2 but haven't cracked it yet.  Any ideas?

(Is multiple templates per NODE/LINK a feature request yet? :)

**Comment by howardjones** [comment]
But this works with OVERLIBGRAPH? That's strange... I agree about the ordering, and if someone uses the editor, this is more or less what the editor does (nodes before links, templates before normal nodes/links)

Multiple templates per link/node probably does work, *at the moment*, because what happens is it copies the template config into the current node as soon as it sees that line. That's why you get a warning if the TEMPLATE isn't the first line in a node. Adding a second one probably would work, but isn't intended to! The idea is supposed to be to build up a hierarchy of less-specific templates: NODE DEFAULT -> Device -> Router -> ASR

So, resolving the text for INFOURL and OVERLIBGRAPH just before the map is output, instead of when the config is read would fix this, and I can't see any impact to anything else. It's should even be a small patch. I'll see if I can come up with something for 0.97, since the current trunk version is in pieces on my driveway.

**Comment by misiek08** [comment]
Offtopic: do you actively develop new (rewritten) version of map or development is now freezed?

**Comment by howardjones** [comment]
Just started looking into this one, and OVERLIBGRAPH and INFOURL are already interpolated late (when the HTML is written out, after all data has been read, and templates resolved). If there's a specific simple test case that doesn't work with the current (database-refactor branch) git version, or 1.0.0 when it comes out, please reopen.
