### ISSUE TITLE
Support for PHP7

### ISSUE THREAD

**Issue by kbabioch** [howardjones/network-weathermap#46]
This projects heavily relies upon mysql_\* functionality from PHP and no other MySQL interface can be chosen, since it is hardcoded. Therefore it does not work with PHP7. The underlying database shouldn't be too much of a deal and should be configurable. At the very least mysql**i** should be used to stay compatible with PHP7.

**Comment by howardjones** [comment]
Please see several other tickets for work in progress moving to PDO. (Sorry, on my phone so no numbers handy)

**Comment by howardjones** [comment]
#33 #34 #38 #43 #44 #45

And: https://network-weathermap.com/2016/09/04/september-2016-current-issues/

This work is happening in the database-refactor branch, and is almost complete.

**Comment by howardjones** [comment]
@kbabioch, are you using weathermap standalone, with Cacti or something else? I assume Cacti, since otherwise the database stuff wouldn't affect you at all.

I think the current database-refactor commit works in PHP 7.0, aside from a couple of obscure rendering issues. I'd be interested to know if you agree. I'd also be interested in knowing more about your environment, if it doesn't - Cacti version, OS etc...

**Comment by jasonkack** [comment]
@howardjones 
0.98a works for me on php7.0.11-1  and cacti 0.8.8h. Thanks for the update

**Comment by kbabioch** [comment]
@howardjones I'm using it in conjuction with Cacti, but I'm having issues with the actual installation. Installing network-weathermap from an official release works just fine, but I'm having trouble with the `database-refactor` branch. I'm trying it in the following way:

- Remove the weathermap directory in Cacti's plugin directory
- Checkout the `database-refactor` branch from the git repostiry
- Invoke make
- Put the content from the resulting archive in Cacti's plugin directory
- Trying to open `Plugin management` from within Cacti

At this point the page stays white. The error log states:

    AH01071: Got error 'PHP message: PHP Warning:  require_once(/usr/share/webapps/cacti/plugins/weathermap/lib/database.php): failed to open stream: No such file or directory in /usr/share/webapps/cacti/plugins/weathermap/setup.php on line 12\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/usr/share/webapps/cacti/plugins/weathermap/lib/database.php' (include_path='.:') in /usr/share/webapps/cacti/plugins/weathermap/setup.php on line 12\n', referer: xxx

The file `/usr/share/webapps/cacti/plugins/weathermap/lib/database.php` is not there in either case (official release vs. self-made release), so maybe some include logic is broken?

@jasonkack: How did you test it? Even when installing the plugin from the official release and then trying to replace all files I run into the same problem and cannot open a single Cacti page.

**Comment by howardjones** [comment]
Aaah. OK. The makefile is what I use to make releases - mostly, it compiles the manual from XML sources, and zips up the file that's uploaded as a release. _However_, it uses the packing.list file to decide what ends up in the zip file. I haven't updated that recently, and there are a lot of new files since 0.98. So instead, for the moment, I'd clone directly into plugins/weathermap. That how I test until very close to release time.

**Comment by kbabioch** [comment]
Ok, after having a look at the Makefile it all makes sense now. For the time being I've basically copied all files from the repository into the plugin directory. This works fine. So far I couldn't spot any problems. Integration with Cacti works fine, although I certainly haven't tested everything yet. Going to do so in the next couple of days. I will report back any problems I encounter. Is there any ETA when this will be released officially?

**Comment by howardjones** [comment]
There is one failing test (or group of tests) related to the precedence of background colours for nodes. There are some changes I still want to add in for the new SNMPv2c and SNMPv3 plugins.
There's some documentation (and obviously packing.list!) to update.

I expect a week or two in real time.

Thanks for your feedback!

**Comment by rprofijt** [comment]
We have an issue when we set the: "SET rrd_use_poller_output 1"  option in the config because we use boost:
Plugin 'weathermap': Uncaught Error: Call to undefined function mysql_real_escape_string() in /opt/cacti/plugins/weathermap/lib/datasources/WeatherMapDataSource_rrd.php:72

We are on the database-refactor branch but the wmrrd_read_from_poller_output function still seems to use php5 code.

If you need anymore info I would be glad to help.

**Comment by howardjones** [comment]
Thanks for the report! This is a known issue - see #45. Several of the data plugins still have outstanding work to switch to PDO database calls.

**Comment by howardjones** [comment]
All mysql_* functions are replaced now.
