### ISSUE TITLE
Dynamically change node (or node label) colour

### ISSUE THREAD

**Issue by jlixfeld** [howardjones/network-weathermap#56]
I'm looking to use NWM as a replacement for a commercial application called InterMapper.  One of the handy features of InterMapper is that the server keeps track of 'packet loss' for a node.  If the server detects a certain level and interval of packet loss, it changes the colour of the node itself to depict that the node is in trouble and to what degree of trouble it's in.

I'm wondering if NWM has the capability to dynamically change a node's (or perhaps a node's label) colour similar to how a change in link bandwidth causes the link colour to change.

**Comment by bhardgrove** [comment]
I use NWM to keep track of both packet loss and latency.  I use a link with latency as the inbound value and packet loss as the outbound value.  I can then use a scale and alarm based on packet loss percent.

I am using elasticsearch as a backend and had to write a datasource plugin to connect weathermaps to elasticsearch.

**Comment by jlixfeld** [comment]
Interesting approach.  So then the latency and loss links are really just pseudo links connected to a fake node that is essentially a placeholder for the latency and loss links? (My understanding is that a link must connect two nodes).

**Comment by howardjones** [comment]
To answer your original question though, you can do this with nodes too. You can add a maximum value, and assign a scale, and a target, just as with links. Nodes only have one colourable element though, instead of two arrows, so you have to pick which of the 'in' and 'out' values to use. Because it shares almost all the code with links, you do still need to specify an in and out target though.
