### ISSUE TITLE
Weathermap 1.0 Map Cycling Feature No longer works correctly

### ISSUE THREAD

**Issue by ikorzha** [howardjones/network-weathermap#90]
In the latest database-refactor revision, Weathermap Cycling Feature no longer works correctly:
Issue 1: If you start full screen cycling with MAP 1 it will stay on the same map on next minute refresh.
If you start on map lets say #4, next minute it will revert to map 1 and stay there every min. Tested under 0.8.8g branch, behavior under Cacti 1.0 seems to be slightly different initially it cycled same map and after a few min started to rotate them....

Issue 2: Cycling "within this group" isn't available in this release and it is a critical feature not to cycle unwanted map under that particular user has access to.

**Comment by howardjones** [comment]
What do you have the cycle time set to in the Cacti settings?
![image](https://cloud.githubusercontent.com/assets/912421/26108449/785b619a-3a44-11e7-8c0f-45ce00c3eb39.png)

**Comment by ikorzha** [comment]
Ok, very interesting behavior when I flip to automatic, it starts cycling but it is very fast because I got 20 maps, It get to map 11 out of 20 then it flips map to 1.
If I flip it to 1min, it continuously cycle map #1 only.  If I put it at 5sec, it cycles maps 1 and 2...
So I think there definitely an issue there.

**Comment by howardjones** [comment]
That sounds like correct (expected, anyway) behaviour, actually. After one poll time, it refreshes and fetches new maps, and restarts the cycle. If you have the cycle interval set to one minute and the poll time also set to one minute, then you will get only the first map before it reloads. As far as I remember, this is how it worked in the version you had before though... (I don't think I actually have a copy - it was the new-style full-screen cycling, right?)

*Desired* behaviour is a different thing :-) It should really refresh each map and carry on cycling from the same point in the cycle instead of resetting. That requires quite a bit of code change so that it can allow for the user adding or removing maps while the display is cycling, or the nodes moving (which means the imagemap has to change).

**Comment by ikorzha** [comment]
I see what you saying. I my old svn 638 it definitely worked differently and much more usable it cycled thru all of the maps in the container until it reached back to 1st one at one min internal. Of course the draw back is the map #20 might be 20min stale as per your logic but it is better than showing same map every min as it is now :)
Think of this way I'm doing 1min Cacti polling and got 20maps. If I have 20 maps and do them automatic first cycle is too fas to be usable. 2nd it doesn't even reach to any maps past 11th before it revers back to 1 due to polling cycle logic

I believe the previous implementation as I described was much more usable and user friendly.

**Comment by ikorzha** [comment]
I hope i can work with you on this issue to come up with usable improvements:)

**Comment by ikorzha** [comment]
I'm good with your current explanation will open a separate feature request for container based map cycling feature that existed previously.
